apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-secret
  namespace: default
type: Opaque
stringData:
  # create this secret with: kubectl create secret generic kubeconfig-secret --from-file=kubeconfig=/path/to/admin.conf
  kubeconfig: |
    # placeholder - replace by creating the secret from file as instructed in README

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-ui
  template:
    metadata:
      labels:
        app: mcp-ui
    spec:
      containers:
      - name: mcp-ui
        image: <your-repo>/mcp-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: mcp-ui-secret
              key: admin-token
        - name: KUBECONFIG_PATH
          value: /etc/kubeconfig/kubeconfig
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubeconfig
          readOnly: true
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret

---
apiVersion: v1
kind: Service
metadata:
  name: mcp-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: mcp-ui
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
